#!/usr/bin/env bash
# Author: MikiasHailu
# Install nginx on your web-01 server
sudo apt-get update
sudo apt-get install -y nginx
sudo utw 'Nginx HTTP'
echo 'Hello World!' | sudo tee /var/www/html/index.html
sudo nginx -t
sudo service nginx reload
